// This file was generated by AutoHeuristic. Do not modify it manually!
// To regenerate this file, take a look at the README.md file inside torchgen/_autoheuristic/depthwise_conv/
#pragma once

#include <ATen/core/Tensor.h>
#include <ATen/detail/CUDAHooksInterface.h>

namespace at::native {


template <typename T>
static bool check_cudnn_depthwise_workload_sm75(
    T stride, T filter, T w, T ch, T bs, T h, T out_h, T out_w,
    T out_elements, T kernel_work) {
  // auto-generated heuristic decision tree for cuDNN SM group 75, tolerance = 0.0
  if (stride <= 1) return true;
  else {
    if (filter <= 4) {
      if (ch <= 48) {
        if (out_elements <= 165888) return true;
        else {
          if (filter <= 2) return false;
          else return true;
        }
      }
      else return true;
    }
    else {
      if (out_w <= 12) return true;
      else return false;
    }
  }
}


template <typename T>
static bool check_cudnn_depthwise_workload_sm80(
    T stride, T filter, T w, T ch, T bs, T h, T out_h, T out_w,
    T out_elements, T kernel_work) {
  // auto-generated heuristic decision tree for cuDNN SM group 80, tolerance = 0.0
  if (stride <= 1) return true;
  else {
    if (ch <= 192) {
      if (filter <= 4) {
        if (filter <= 2) {
          if (bs <= 2) return true;
          else {
            if (out_elements <= 3178496) {
              if (w <= 17) return true;
              else return false;
            }
            else return true;
          }
        }
        else return true;
      }
      else {
        if (h <= 17) return true;
        else {
          if (kernel_work <= 67276800) return false;
          else return true;
        }
      }
    }
    else {
      if (bs <= 2) {
        if (filter <= 4) return true;
        else return false;
      }
      else return true;
    }
  }
}


template <typename T>
static bool check_cudnn_depthwise_workload_sm86(
    T stride, T filter, T w, T ch, T bs, T h, T out_h, T out_w,
    T out_elements, T kernel_work) {
  // auto-generated heuristic decision tree for cuDNN SM group 86, tolerance = 0.0
  if (stride <= 1) return true;
  else {
    if (filter <= 4) {
      if (ch <= 80) {
        if (out_elements <= 165888) return true;
        else {
          if (filter <= 2) return false;
          else {
            if (ch <= 48) return false;
            else return true;
          }
        }
      }
      else {
        if (ch <= 112) {
          if (filter <= 2) {
            if (out_elements <= 182784) return true;
            else return false;
          }
          else return true;
        }
        else return true;
      }
    }
    else {
      if (out_w <= 12) return true;
      else return false;
    }
  }
}


template <typename T>
static bool check_cudnn_depthwise_workload_sm89(
    T stride, T filter, T w, T ch, T bs, T h, T out_h, T out_w,
    T out_elements, T kernel_work) {
  // auto-generated heuristic decision tree for cuDNN SM group 89, tolerance = 0.0
  if (stride <= 1) return true;
  else {
    if (ch <= 192) {
      if (out_h <= 9) {
        if (ch <= 48) return false;
        else return true;
      }
      else {
        if (bs <= 48) {
          if (bs <= 2) {
            if (filter <= 4) {
              if (kernel_work <= 115712) return false;
              else return true;
            }
            else return false;
          }
          else {
            if (filter <= 4) {
              if (filter <= 2) return false;
              else {
                if (ch <= 48) return false;
                else return true;
              }
            }
            else return false;
          }
        }
        else {
          if (kernel_work <= 27557888) return false;
          else return true;
        }
      }
    }
    else {
      if (out_w <= 12) return true;
      else {
        if (filter <= 4) {
          if (kernel_work <= 3178496) {
            if (bs <= 2) return true;
            else return false;
          }
          else return true;
        }
        else {
          if (bs <= 12) return false;
          else return true;
        }
      }
    }
  }
}


template <typename T>
static bool check_cudnn_depthwise_workload_sm90(
    T stride, T filter, T w, T ch, T bs, T h, T out_h, T out_w,
    T out_elements, T kernel_work) {
  // auto-generated heuristic decision tree for cuDNN SM group 90, tolerance = 0.0
  if (stride <= 1) {
    if (kernel_work <= 220416) {
      if (bs <= 6) return true;
      else return false;
    }
    else return true;
  }
  else {
    if (ch <= 192) {
      if (filter <= 4) {
        if (filter <= 2) {
          if (bs <= 2) return true;
          else {
            if (kernel_work <= 49664) return true;
            else return false;
          }
        }
        else {
          if (ch <= 48) {
            if (w <= 38) return false;
            else return true;
          }
          else return true;
        }
      }
      else return false;
    }
    else {
      if (out_w <= 12) return true;
      else {
        if (filter <= 4) {
          if (filter <= 2) {
            if (bs <= 2) return true;
            else {
              if (ch <= 768) return false;
              else return true;
            }
          }
          else return true;
        }
        else return false;
      }
    }
  }
}


template <typename T>
static bool check_cudnn_depthwise_workload_sm100(
    T stride, T filter, T w, T ch, T bs, T h, T out_h, T out_w,
    T out_elements, T kernel_work) {
  // auto-generated heuristic decision tree for cuDNN SM group 100, tolerance = 0.0
  if (stride <= 1) return true;
  else {
    if (ch <= 112) {
      if (out_elements <= 3178496) {
        if (out_w <= 4) return true;
        else {
          if (kernel_work <= 35200) return true;
          else {
            if (out_h <= 50) {
              if (filter <= 2) return false;
              else {
                if (ch <= 48) return false;
                else {
                  if (h <= 17) {
                    if (h <= 12) return false;
                    else return true;
                  }
                  else {
                    if (bs <= 24) {
                      if (filter <= 4) {
                        if (kernel_work <= 1787904) {
                          if (out_elements <= 57856) return false;
                          else return true;
                        }
                        else return false;
                      }
                      else return false;
                    }
                    else {
                      if (out_elements <= 1728512) return false;
                      else return true;
                    }
                  }
                }
              }
            }
            else {
              if (filter <= 4) {
                if (bs <= 2) return true;
                else {
                  if (kernel_work <= 5185536) return false;
                  else return true;
                }
              }
              else return false;
            }
          }
        }
      }
      else return true;
    }
    else {
      if (filter <= 2) {
        if (ch <= 768) {
          if (out_w <= 4) return true;
          else {
            if (kernel_work <= 9011200) {
              if (bs <= 2) return true;
              else {
                if (kernel_work <= 3633152) {
                  if (w <= 24) {
                    if (bs <= 12) return true;
                    else return false;
                  }
                  else return false;
                }
                else return false;
              }
            }
            else return true;
          }
        }
        else return true;
      }
      else {
        if (bs <= 2) {
          if (w <= 24) return true;
          else {
            if (filter <= 4) {
              if (w <= 60) {
                if (ch <= 704) return false;
                else return true;
              }
              else return true;
            }
            else return false;
          }
        }
        else {
          if (ch <= 192) {
            if (bs <= 10) {
              if (kernel_work <= 1844224) return true;
              else return false;
            }
            else return true;
          }
          else return true;
        }
      }
    }
  }
}


template <typename T>
static bool check_cudnn_depthwise_workload_sm120(
    T stride, T filter, T w, T ch, T bs, T h, T out_h, T out_w,
    T out_elements, T kernel_work) {
  // auto-generated heuristic decision tree for cuDNN SM group 120, tolerance = 0.0
  if (stride <= 1) {
    if (kernel_work <= 278528) {
      if (out_h <= 17) {
        if (kernel_work <= 46256) return false;
        else return true;
      }
      else return true;
    }
    else return true;
  }
  else {
    if (out_h <= 9) {
      if (ch <= 112) {
        if (w <= 10) {
          if (out_elements <= 8192) return false;
          else return true;
        }
        else return false;
      }
      else {
        if (out_elements <= 638976) return true;
        else return false;
      }
    }
    else {
      if (kernel_work <= 202752) {
        if (bs <= 6) {
          if (out_elements <= 14688) return false;
          else return true;
        }
        else return false;
      }
      else {
        if (out_h <= 12) {
          if (bs <= 20) return true;
          else return false;
        }
        else {
          if (filter <= 2) {
            if (kernel_work <= 21233664) {
              if (bs <= 2) {
                if (kernel_work <= 598016) return true;
                else return false;
              }
              else return false;
            }
            else {
              if (ch <= 768) return false;
              else return true;
            }
          }
          else return false;
        }
      }
    }
  }
}


template <typename T>
static bool check_cudnn_depthwise_workload_with_filter(
    const at::Tensor& input, T stride, const at::Tensor& weight) {
  const int sm = at::detail::getCUDAHooks().getDeviceCapability(
      input.get_device());
  TORCH_INTERNAL_ASSERT(sm != 0, "CUDA not available");

  // 1D conv
  if (at::symint::size<T>(input, 2) == 1 && stride == 1) {
    return true;
  }
  // 2D conv
  // only 1/2 stride
  if (stride != 1 && stride != 2) return false;
  // only square filters
  if (at::symint::size<T>(weight, 2) !=
      at::symint::size<T>(weight, 3)) {
    return false;
  }
  auto filter = at::symint::size<T>(weight, 3);
  // only 1/3/5 filter
  if (filter != 1 && filter != 3 && filter != 5) return false;
  auto h = at::symint::size<T>(input, 2);
  auto w = at::symint::size<T>(input, 3);
  if (h < 7) return false;
  if (w < 7) return false;
  auto ch = at::symint::size<T>(input, 1);
  auto bs = at::symint::size<T>(input, 0);
  auto out_h = (h + 2 * (filter / 2) - filter) / stride + 1;
  auto out_w = (w + 2 * (filter / 2) - filter) / stride + 1;
  auto out_elements = bs * ch * out_h * out_w;
  auto kernel_work = out_elements * filter * filter;

  if (sm < 80) return check_cudnn_depthwise_workload_sm75<T>(
      stride, filter, w, ch, bs, h, out_h, out_w,
      out_elements, kernel_work);
  if (sm < 86) return check_cudnn_depthwise_workload_sm80<T>(
      stride, filter, w, ch, bs, h, out_h, out_w,
      out_elements, kernel_work);
  if (sm < 89) return check_cudnn_depthwise_workload_sm86<T>(
      stride, filter, w, ch, bs, h, out_h, out_w,
      out_elements, kernel_work);
  if (sm < 90) return check_cudnn_depthwise_workload_sm89<T>(
      stride, filter, w, ch, bs, h, out_h, out_w,
      out_elements, kernel_work);
  if (sm < 100) return check_cudnn_depthwise_workload_sm90<T>(
      stride, filter, w, ch, bs, h, out_h, out_w,
      out_elements, kernel_work);
  if (sm < 120) return check_cudnn_depthwise_workload_sm100<T>(
      stride, filter, w, ch, bs, h, out_h, out_w,
      out_elements, kernel_work);
  return check_cudnn_depthwise_workload_sm120<T>(
      stride, filter, w, ch, bs, h, out_h, out_w,
      out_elements, kernel_work);
}


} // namespace at::native
